name = "aiken/gift_card"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken/gift_card'"

[repository]
user = "aiken"
project = "gift_card"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.6.0"
source = "github"
